project:
  type: website

website:
  title: "Yigong Hu's Supplemental Materials for GIScience"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/HPDell/
format:
  html:
    theme: flatly
    css: styles.css



